# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{accountable}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason Harrelson"]
  s.date = %q{2010-05-10}
  s.description = %q{An abstraction of the account / user pattern.  The account owns all of the system assets and users are delegated permissions to them.}
  s.email = %q{jason@lookforwardenterprises.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "accountable.gemspec",
     "lib/accountable.rb",
     "lib/accountable/accountee.rb",
     "lib/accountable/accountor.rb",
     "lib/accountable/accountor/states.rb",
     "lib/accountable/accountor/states/aasm_traits.rb",
     "lib/accountable/accountor/states/state_machine_instance_methods.rb",
     "lib/accountable/accountor/states/state_machine_traits.rb",
     "lib/accountable/accountors_asset.rb",
     "lib/accountable/active_record_extensions.rb",
     "lib/accountable/controller_actions.rb",
     "lib/accountable/controller_helpers.rb",
     "lib/accountable/current_methods.rb",
     "lib/accountable/matchers.rb",
     "lib/accountable/matchers/acts_as_accountor_matcher.rb",
     "lib/accountable/view_helpers.rb",
     "spec/accountable_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/midas/accountable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{An abstraction of the account / user pattern.}
  s.test_files = [
    "spec/accountable_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

